#!/bin/bash

# Used to start the application in the production environment (Docker)

set -x

python manage.py migrate --noinput
python manage.py collectstatic --noinput --clear

#exec gunicorn app.wsgi:application \
#  --bind 0.0.0.0:8000 \
#  --workers 4 \
#  --log-file=/dev/stdout

exec uwsgi --wsgi-file app/wsgi.py --master --processes 4 --threads 2