#!/bin/bash

# Used to start the application in the production environment (Docker)

set -x

python manage.py migrate --noinput
python manage.py collectstatic --noinput --clear

exec uwsgi --wsgi-file app/wsgi.py --master --processes 4